controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  chassis_controller:
    # ChassisBase
    type: chassis_controllers/SwerveController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: false
    publish_odom_tf: false
    power:
      effort_coeff: 10.0
      vel_coeff: 0.0060
      power_offset: -8.41
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 5.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # SwerveController
    modules:
      left_front:
        position: [ 0.175, 0.175 ]
        pivot:
          joint: left_front_pivot_joint
          <<: &pivot_setting
            offset: 0.
            pid: { p: 5, i: 50, d: 0, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
        wheel:
          joint: left_front_wheel_joint
          <<: &wheel_setting
            radius: 0.049
            pid: { p: 0.4, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        position: [ 0.175, -0.175 ]
        pivot:
          joint: right_front_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: right_front_wheel_joint
          <<: *wheel_setting
      left_back:
        position: [ -0.175, 0.175 ]
        pivot:
          joint: left_back_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: left_back_wheel_joint
          <<: *wheel_setting
      right_back:
        position: [ -0.175, -0.175 ]
        pivot:
          joint: right_back_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: right_back_wheel_joint
          <<: *wheel_setting

  action_controller:
    type: action_controller/Controller
    action_names: # action names
      - location_action
    pub_odom_tf: true # default use data of the first action as pub_odom_tf data source
    pub_action_data: true
    pub_rate: 100.0
    # twist covariance of (x, y, z, r, p, y)
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]