controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  #  rc_robot_state_publisher:
  #    type: rc_robot_state_publisher/RcRobotStatePublisher
  #    publish_rate: 100

  chassis_controller:
    # ChassisBase
    type: chassis_controllers/SwerveController
    wheel_track: 0.3
    wheel_base: 0.3
    wheel_radius: 0.054
    publish_rate: 100
    timeout: 0.1
    pid_follow: { p: 5.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    # SwerveController
    modules:
      left_front:
        position: [ 0.15, 0.15 ]
        pivot:
          joint: left_front_pivot_joint
          <<: &pivot_setting
            offset: 0.
            pid: { p: 0.5, i: 0.5, d: 0, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
        wheel:
          joint: left_front_wheel_joint
          <<: &wheel_setting
            radius: 0.054
            pid: { p: 0.5, i: 0.1, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        position: [ 0.15, -0.15 ]
        pivot:
          joint: right_front_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: right_front_wheel_joint
          <<: *wheel_setting
      left_back:
        position: [ -0.15, 0.15 ]
        pivot:
          joint: left_back_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: left_back_wheel_joint
          <<: *wheel_setting
      right_back:
        position: [ -0.15, -0.15 ]
        pivot:
          joint: right_back_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: right_back_wheel_joint
          <<: *wheel_setting

  action_controller:
    type: action_controller/Controller
    action_names: # action names
      - location_action
    pub_odom_tf: true # default use data of the first action as pub_odom_tf data source
    pub_action_data: true
    pub_rate: 100.0
    # twist covariance of (x, y, z, r, p, y)
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

